site:
  name: WordRocket
  site: 'https://wordrocket.ai'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: false

# Default SEO metadata
metadata:
  title:
    default: WordRocket - AI Content Generation Platform
    template: '%s | WordRocket'
  description: "🚀 Generate high-quality, SEO-optimized content with AI. Access GPT-4, Claude, Gemini & more. Save time and boost your content marketing with WordRocket."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: WordRocket
    images:
      - url: '~/assets/images/wordrocket-og.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@wordrocket'
    site: '@wordrocket'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/blog/%slug%'
      robots:
        index: true

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # Add your GA4 ID here

ui:
  theme: 'system'